version: '3.8'

x-env: &x-env
  env_file:
    - .env

services:

  nginx:
    image: nginx:1.23.0
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
      - ./static:/var/www
    depends_on:
      - admin
      - api
    ports:
      - "80:80"

  admin:
    build: ./admin
    volumes:
      - ./static:/var/www
    depends_on:
      - db
    <<: *x-env

  api:
    build: ./event_api
    depends_on:
      - rabbit
    <<: *x-env

  worker:
    build:
      context: ./worker
    depends_on:
      - rabbit
    <<: *x-env

  scheduler:
    build:
      context: ./scheduler
    depends_on:
      - db
      - rabbit
    <<: *x-env

  db:
    image: postgres:13.2-alpine
    restart: on-failure
    <<: *x-env

  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "15672:15672"

  fake-server:
    build:
      context: ./fake_server
    ports:
      - "4000:4000"

  tests:
    build: ./tests
    entrypoint: /opt/tests/docker-entrypoint.sh
    depends_on:
      - api